services:
  - type: web
    name: furnispace
    env: node
    plan: free
    buildCommand: npm install && node database/seed.js
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: SITE_URL
        sync: false
